import { md } from 'cuirk'
import meta from '../data/meta.js'

export const body = md`
# ${meta.title}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut imperdiet sit amet leo id suscipit. Proin augue velit, posuere eget iaculis non, feugiat accumsan mi. Phasellus accumsan magna a posuere fermentum. Nullam interdum rhoncus finibus. Integer aliquet sit amet justo imperdiet fermentum. Phasellus lobortis pharetra ipsum. Aenean id placerat mi. Donec blandit nibh quis turpis luctus, at facilisis erat vestibulum. Donec quis sodales nisi. Vestibulum ac nibh laoreet nunc rutrum ornare. Ut nisi mauris, tempor quis molestie vel, commodo non lectus. Donec eu neque venenatis, euismod nisi ac, sodales tortor.

Maecenas interdum vestibulum ultrices. Curabitur pharetra eros vel mi eleifend, sit amet vulputate nisi laoreet. Sed consectetur tellus in neque scelerisque, id varius neque tempus. Suspendisse in odio a elit aliquam dignissim. Nullam ornare risus et ante lacinia, at interdum eros pharetra. Donec nec erat erat. Vestibulum ligula velit, pulvinar at vulputate ac, cursus nec augue. Fusce ornare massa feugiat varius rutrum. Morbi sit amet ligula pulvinar, iaculis turpis in, accumsan mi. Nullam et consectetur quam.

Duis tristique ex in mauris fermentum, et luctus orci egestas. Vivamus ac commodo mi. Nulla maximus egestas dolor, nec volutpat ante dignissim id. Proin nec nulla placerat, blandit augue eget, tincidunt elit. Morbi eu pulvinar odio. Nam nec lectus nec metus vestibulum hendrerit. Morbi pharetra, nulla eu tincidunt ultricies, lorem sem feugiat leo, eu scelerisque magna tellus ut sapien. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In cursus sit amet magna eu tempus. Duis hendrerit vel lectus in finibus. Vivamus sit amet vehicula metus, eu efficitur ante. Vivamus volutpat ex ut justo sodales, nec tempus felis gravida. Praesent aliquam vulputate est, eu mollis justo feugiat ut. Phasellus sodales ex quis sem hendrerit, molestie varius urna tempus.

Nunc dolor orci, feugiat id massa ut, placerat pharetra augue. Aliquam lobortis vel diam eget laoreet. Fusce lobortis ante eget nulla imperdiet egestas porttitor sed nunc. Integer eu diam quis erat semper molestie nec nec nulla. Proin id lacus nisl. Pellentesque fermentum tellus ut nibh vestibulum mattis. Vestibulum molestie a ante sed eleifend. Phasellus egestas sem pulvinar, commodo dui sed, lobortis magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed placerat scelerisque enim et placerat. Ut accumsan, lacus a gravida euismod, felis nulla sodales odio, et faucibus tellus augue sed sapien. Duis eu feugiat neque. Praesent vehicula tempus lectus quis interdum. Phasellus et ornare ex.

Quisque elit eros, semper id interdum sit amet, ullamcorper eget velit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a malesuada erat. Aliquam id vestibulum mi, vel iaculis nisi. Curabitur varius massa tempus nunc egestas maximus. Cras elementum, sapien a tempus sodales, sem mauris vulputate nibh, a fermentum libero sapien ut est. Nulla efficitur vestibulum ultrices. Etiam nec mi dapibus, mollis neque id, vulputate lectus. Mauris porttitor volutpat urna, quis interdum augue efficitur eu. Maecenas sollicitudin, dolor sit amet porta ornare, dolor nisi aliquet ex, eu fermentum urna mi nec eros. Maecenas facilisis neque sit amet rutrum laoreet. Etiam vitae consectetur libero, vitae suscipit ante. Donec lacinia, sem sit amet semper aliquam, risus risus mollis erat, ac fermentum lacus erat id tellus.
`
